"""
Idea Generator - LLM-powered token concept generation.

Generates novel shitcoin ideas autonomously based on:
- Current market trends
- Successful historical patterns
- Creative meme combinations
- Gap analysis in the market
"""

import json
import random
from dataclasses import dataclass, field
from typing import Optional
from enum import Enum

import anthropic

from ..models.token import MemeStyle, MarketCondition


class IdeaStrategy(str, Enum):
    """Different strategies for generating token ideas."""
    TREND_CHASE = "trend_chase"       # Follow current CT meta
    CONTRARIAN = "contrarian"          # Go against current narrative
    REMIX = "remix"                    # Combine existing successful elements
    AVANT_GARDE = "avant_garde"        # Experimental, weird concepts
    NOSTALGIA = "nostalgia"            # Throwback to past memes/culture
    TOPICAL = "topical"                # Current events/news driven


@dataclass
class GeneratedIdea:
    """A token concept generated by the AI."""
    name: str
    ticker: str
    narrative: str
    tagline: str
    meme_style: MemeStyle
    hook: str                          # The viral angle
    target_audience: str
    strategy: IdeaStrategy
    reasoning: str                     # Why this might work
    risk_factors: list[str]            # Potential problems
    confidence: float                  # Generator's confidence (0-1)

    # Generation metadata
    generation_prompt: str = ""
    raw_response: str = ""

    def to_token_dict(self) -> dict:
        """Convert to Token-compatible dict."""
        return {
            "name": self.name,
            "ticker": self.ticker,
            "narrative": self.narrative,
            "tagline": self.tagline,
            "meme_style": self.meme_style,
        }


GENERATION_PROMPT = """You are a shitcoin ideation machine. Your job is to generate novel,
potentially viral token concepts for Crypto Twitter (CT).

You understand CT culture deeply:
- Memes are the language of CT
- Absurdity often wins over substance
- Timing and narrative matter more than utility
- Community and vibes beat features
- Self-awareness and irony are valued
- Dogs, frogs, and cats have proven track records
- AI narrative is currently strong
- Meta plays (coins about coins) can work

Your ideas should be:
1. MEMORABLE - Easy to remember name/ticker
2. SHAREABLE - Contains viral hook that makes people want to tweet
3. TIMELY - Fits current CT mood and trends
4. DIFFERENTIATED - Not just another clone
5. MEME-ABLE - Easy to create content around

Generate token concepts that could realistically trend on CT.
Be creative but grounded in what actually works on CT."""


class IdeaGenerator:
    """Generates token concepts using LLM creativity."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: str = "claude-sonnet-4-20250514",
    ):
        self.client = anthropic.Anthropic(api_key=api_key) if api_key else None
        self.model = model
        self.generation_history: list[GeneratedIdea] = []

    def generate(
        self,
        strategy: Optional[IdeaStrategy] = None,
        market_condition: MarketCondition = MarketCondition.CRAB,
        constraints: Optional[dict] = None,
        num_ideas: int = 1,
    ) -> list[GeneratedIdea]:
        """
        Generate token ideas.

        Args:
            strategy: Generation strategy (random if None)
            market_condition: Current market state
            constraints: Optional constraints like {"must_include": "dog", "avoid": ["AI"]}
            num_ideas: Number of ideas to generate
        """
        if not self.client:
            return self._generate_fallback(num_ideas)

        strategy = strategy or random.choice(list(IdeaStrategy))

        prompt = self._build_prompt(strategy, market_condition, constraints, num_ideas)

        response = self.client.messages.create(
            model=self.model,
            max_tokens=2000,
            system=GENERATION_PROMPT,
            messages=[{"role": "user", "content": prompt}],
        )

        raw_response = response.content[0].text
        ideas = self._parse_response(raw_response, strategy, prompt)

        self.generation_history.extend(ideas)
        return ideas

    def generate_variations(
        self,
        base_idea: GeneratedIdea,
        num_variations: int = 3,
    ) -> list[GeneratedIdea]:
        """Generate variations on an existing idea."""
        if not self.client:
            return []

        prompt = f"""Generate {num_variations} variations on this token concept:

Original:
- Name: {base_idea.name}
- Ticker: ${base_idea.ticker}
- Narrative: {base_idea.narrative}
- Hook: {base_idea.hook}

Create variations that:
1. Keep the core appeal but change the angle
2. Try different meme styles
3. Explore adjacent niches

Return JSON array of variations."""

        response = self.client.messages.create(
            model=self.model,
            max_tokens=2000,
            system=GENERATION_PROMPT,
            messages=[{"role": "user", "content": prompt}],
        )

        return self._parse_response(response.content[0].text, base_idea.strategy, prompt)

    def brainstorm(
        self,
        theme: str,
        num_ideas: int = 5,
    ) -> list[GeneratedIdea]:
        """Brainstorm ideas around a specific theme."""
        if not self.client:
            return self._generate_fallback(num_ideas)

        prompt = f"""Brainstorm {num_ideas} shitcoin concepts around this theme: "{theme}"

Explore different angles:
- Literal interpretations
- Ironic/satirical takes
- Cultural references
- Unexpected combinations

Return JSON array with your ideas."""

        response = self.client.messages.create(
            model=self.model,
            max_tokens=2500,
            system=GENERATION_PROMPT,
            messages=[{"role": "user", "content": prompt}],
        )

        return self._parse_response(response.content[0].text, IdeaStrategy.REMIX, prompt)

    def _build_prompt(
        self,
        strategy: IdeaStrategy,
        market_condition: MarketCondition,
        constraints: Optional[dict],
        num_ideas: int,
    ) -> str:
        """Build the generation prompt based on strategy."""

        strategy_prompts = {
            IdeaStrategy.TREND_CHASE: """Generate ideas that follow current CT trends.
Think about what's hot right now: AI agents, meme coins, cultural moments.
Ride the wave - what would CT be excited about TODAY?""",

            IdeaStrategy.CONTRARIAN: """Generate contrarian ideas that go AGAINST current narratives.
When everyone zigs, zag. If CT is obsessed with AI, maybe go analog.
If everyone's bullish, create something that embraces the bear.
Counter-culture plays can work when the timing is right.""",

            IdeaStrategy.REMIX: """Generate ideas that combine successful elements from past tokens.
Mix and match: Doge's community + Pepe's meme power + AI narrative.
What Frankenstein combinations could capture multiple audiences?""",

            IdeaStrategy.AVANT_GARDE: """Generate weird, experimental, boundary-pushing concepts.
Think art projects, social experiments, absurdist humor.
The kind of thing that makes people go "wtf" then share it.""",

            IdeaStrategy.NOSTALGIA: """Generate ideas that tap into nostalgia.
Early internet culture, 90s/2000s memes, childhood memories.
What makes CT feel warm and fuzzy about the past?""",

            IdeaStrategy.TOPICAL: """Generate ideas tied to current events or news.
What's happening in the world right now that CT is talking about?
Timely plays that capture a moment.""",
        }

        market_context = {
            MarketCondition.BEAR: "Market is down - people are scared and cynical. Humor and community matter more than hype.",
            MarketCondition.CRAB: "Market is sideways - people are bored, looking for entertainment. Good time for novel concepts.",
            MarketCondition.BULL: "Market is up - people are greedy and FOMO-driven. High energy plays work.",
            MarketCondition.EUPHORIA: "Market is euphoric - anything can pump. Absurdity reaches peak levels.",
        }

        prompt = f"""Strategy: {strategy.value}
{strategy_prompts[strategy]}

Market Context ({market_condition.value}): {market_context[market_condition]}

"""

        if constraints:
            if "must_include" in constraints:
                prompt += f"MUST include: {constraints['must_include']}\n"
            if "avoid" in constraints:
                prompt += f"AVOID: {', '.join(constraints['avoid'])}\n"
            if "target_audience" in constraints:
                prompt += f"Target audience: {constraints['target_audience']}\n"

        prompt += f"""
Generate {num_ideas} token concept(s).

Return as JSON array:
[
  {{
    "name": "Full token name",
    "ticker": "TICKER",
    "narrative": "The story - why this exists, why people should care",
    "tagline": "One-liner catchphrase",
    "meme_style": "cute|edgy|absurd|topical|nostalgic",
    "hook": "The viral angle - what makes people share this",
    "target_audience": "Who this is for",
    "reasoning": "Why this might work on CT",
    "risk_factors": ["potential problems"],
    "confidence": 0.0-1.0
  }}
]

Be specific and creative. Each idea should be distinct."""

        return prompt

    def _parse_response(
        self,
        response: str,
        strategy: IdeaStrategy,
        prompt: str,
    ) -> list[GeneratedIdea]:
        """Parse LLM response into GeneratedIdea objects."""
        ideas = []

        try:
            # Find JSON array in response
            start = response.find("[")
            end = response.rfind("]") + 1

            if start >= 0 and end > start:
                data = json.loads(response[start:end])

                for item in data:
                    # Map meme_style string to enum
                    style_str = item.get("meme_style", "absurd").lower()
                    style_map = {
                        "cute": MemeStyle.CUTE,
                        "edgy": MemeStyle.EDGY,
                        "absurd": MemeStyle.ABSURD,
                        "topical": MemeStyle.TOPICAL,
                        "nostalgic": MemeStyle.NOSTALGIC,
                    }
                    meme_style = style_map.get(style_str, MemeStyle.ABSURD)

                    idea = GeneratedIdea(
                        name=item.get("name", "Unknown"),
                        ticker=item.get("ticker", "UNK"),
                        narrative=item.get("narrative", ""),
                        tagline=item.get("tagline", ""),
                        meme_style=meme_style,
                        hook=item.get("hook", ""),
                        target_audience=item.get("target_audience", "degens"),
                        strategy=strategy,
                        reasoning=item.get("reasoning", ""),
                        risk_factors=item.get("risk_factors", []),
                        confidence=float(item.get("confidence", 0.5)),
                        generation_prompt=prompt,
                        raw_response=response,
                    )
                    ideas.append(idea)

        except (json.JSONDecodeError, KeyError, ValueError) as e:
            # Fallback: try to extract any useful info
            pass

        return ideas

    def _generate_fallback(self, num_ideas: int) -> list[GeneratedIdea]:
        """Generate template-based ideas when no API key."""
        templates = [
            GeneratedIdea(
                name="Based Dog",
                ticker="BASED",
                narrative="The most based dog on the blockchain",
                tagline="Stay based, stay winning",
                meme_style=MemeStyle.CUTE,
                hook="Community-first dog coin for true degens",
                target_audience="degens",
                strategy=IdeaStrategy.TREND_CHASE,
                reasoning="Dog coins have proven track record",
                risk_factors=["Saturated market"],
                confidence=0.5,
            ),
            GeneratedIdea(
                name="Artificial Frog",
                ticker="AIFROG",
                narrative="AI meets Pepe - the smartest frog in crypto",
                tagline="Ribbit with intelligence",
                meme_style=MemeStyle.ABSURD,
                hook="What if Pepe had a brain?",
                target_audience="tech degens",
                strategy=IdeaStrategy.REMIX,
                reasoning="Combines AI trend with proven meme",
                risk_factors=["Derivative concept"],
                confidence=0.6,
            ),
            GeneratedIdea(
                name="Nothing Coin",
                ticker="NOTHING",
                narrative="A coin about literally nothing. No utility. No promises. Just vibes.",
                tagline="Embrace the void",
                meme_style=MemeStyle.ABSURD,
                hook="The most honest shitcoin ever",
                target_audience="nihilistic degens",
                strategy=IdeaStrategy.CONTRARIAN,
                reasoning="Radical honesty might be refreshing",
                risk_factors=["Too meta"],
                confidence=0.4,
            ),
            GeneratedIdea(
                name="Dial-Up",
                ticker="DIALUP",
                narrative="Remember waiting 5 minutes to see one image? We're bringing that back.",
                tagline="Slow is the new fast",
                meme_style=MemeStyle.NOSTALGIC,
                hook="Nostalgia for the early internet era",
                target_audience="millennials",
                strategy=IdeaStrategy.NOSTALGIA,
                reasoning="Nostalgia plays well with older CT",
                risk_factors=["Limited audience"],
                confidence=0.5,
            ),
        ]

        random.shuffle(templates)
        return templates[:num_ideas]
